# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build the image
        run: |
          docker build -t mynode -f Dockerfile .
          docker create -ti --name dummy mynode bash
          docker cp dummy:/build/index.html index.html
          docker rm -f dummy

      - name: Deploy to gh-pages branch
        # only push to gh-pages if we're on the deploy branch
        if:  ${{ github.ref == 'refs/heads/deploy' }}
        uses: dsayling/commit-branch-check-action@v0.0.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: " Deploy ${{ github.repository }} gh-pages branch"
          dest-branch: gh-pages
